# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170608_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'blog authors'},
        ),
    ]
